version: '3.8'

services:
  mysqldb:
    image: mysql:8
    restart: always
    env_file: 
      - ./.env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: todoapp
    env_file: 
      ./.env.dev
    ports:
      - ${PORT}:${PORT}
    volumes: 
        - ./:/app
        - app/node_modules
    depends_on:
        - mysqldb
    stdin_open: true
    tty: true
  
volumes: 
  db-config:
  db-data: